SELECT t.TABLE_SCHEMA, t.TABLE_NAME, 
       CASE WHEN p.PARTITION_NAME IS NOT NULL THEN 'YES' ELSE 'NO' END AS HAS_PARTITION
FROM information_schema.tables t
LEFT JOIN information_schema.partitions p
ON t.TABLE_SCHEMA = p.TABLE_SCHEMA AND t.TABLE_NAME = p.TABLE_NAME
GROUP BY t.TABLE_SCHEMA, t.TABLE_NAME;